In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../data/dataset.csv')

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [5]:
df.set_index('Row ID', inplace=True)

In [6]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [7]:
df.describe()

        Postal Code         Sales
count   9789.000000   9800.000000
mean   55273.322403    230.769059
std    32041.223413    626.651875
min     1040.000000      0.444000
25%    23223.000000     17.248000
50%    58103.000000     54.490000
75%    90008.000000    210.605000
max    99301.000000  22638.480000

In [8]:
df['Sales'].median()

np.float64(54.489999999999995)

In [26]:
country_gap=df.groupby('City')
# country_gap.get_group('United States')

In [40]:
country_gap[['Sales','Segment','Customer Name','Ship Date']].value_counts().loc['Henderson']

Sales     Segment      Customer Name     Ship Date
261.960   Consumer     Claire Gute       11/11/2017    1
731.940   Consumer     Claire Gute       11/11/2017    1
152.940   Consumer     Darren Koutras    11/12/2016    1
283.920   Consumer     Darren Koutras    11/12/2016    1
10.670    Consumer     Rob Dowd          03/11/2016    1
36.630    Consumer     Rob Dowd          03/11/2016    1
24.100    Consumer     Rob Dowd          03/11/2016    1
33.110    Consumer     Rob Dowd          03/11/2016    1
196.450   Corporate    Adam Hart         18/04/2018    1
94.740    Corporate    Karen Carlisle    03/01/2017    1
60.640    Corporate    Karen Carlisle    03/01/2017    1
76.300    Corporate    Karen Carlisle    03/01/2017    1
364.800   Corporate    Karen Carlisle    03/01/2017    1
821.880   Consumer     Adrian Barton     23/11/2018    1
21.960    Consumer     Adrian Barton     23/11/2018    1
61.000    Home Office  Daniel Byrd       02/04/2018    1
671.930   Home Office  Daniel Byrd       02/04/2018    1
83.250    Corporate    Sean Braxton      09/05/2015    1
9.450     Corporate    Sean Braxton      09/05/2015    1
20.650    Corporate    Sean Braxton      09/05/2015    1
45.360    Corporate    Sean Braxton      09/05/2015    1
17.480    Home Office  Paul Stevenson    02/12/2016    1
71.880    Home Office  Paul Stevenson    02/12/2016    1
20.000    Consumer     Arthur Prichep    08/11/2017    1
7.980     Consumer     Arthur Prichep    08/11/2017    1
24.100    Consumer     Arthur Prichep    08/11/2017    1
8.750     Consumer     Arthur Prichep    08/11/2017    1
842.940   Consumer     Arthur Prichep    08/11/2017    1
27.580    Home Office  Sample Company A  25/11/2018    1
5.320     Corporate    Thomas Boland     05/11/2018    1
975.920   Corporate    Thomas Boland     05/11/2018    1
2249.910  Corporate    Thomas Boland     05/11/2018    1
59.920    Corporate    Thomas Boland     05/11/2018    1
106.320   Consumer     Craig Carroll     13/01/2016    1
163.440   Consumer     Craig Carroll     13/01/2016    1
42.760    Consumer     Craig Carroll     13/01/2016    1
51.550    Consumer     Craig Carroll     13/01/2016    1
1685.880  Corporate    Lindsay Williams  06/05/2017    1
5.728     Corporate    Lindsay Williams  06/05/2017    1
2573.820  Home Office  Maria Etezadi     10/01/2015    1
609.980   Home Office  Maria Etezadi     10/01/2015    1
5.480     Home Office  Maria Etezadi     10/01/2015    1
391.980   Home Office  Maria Etezadi     10/01/2015    1
755.960   Home Office  Maria Etezadi     10/01/2015    1
31.120    Home Office  Maria Etezadi     10/01/2015    1
6.540     Home Office  Maria Etezadi     10/01/2015    1
12.390    Corporate    Kimberly Carter   15/12/2015    1
828.840   Corporate    Dorothy Badders   26/04/2015    1
318.080   Consumer     Giulietta Weimer  23/02/2017    1
5.800     Consumer     Giulietta Weimer  23/02/2017    1
1577.940  Consumer     Alan Hwang        06/09/2018    1
Name: count, dtype: int64

In [48]:
country_gap['Sales'].agg(['median','mean','sum'])

              median        mean       sum
City
Aberdeen      25.500   25.500000    25.500
Abilene        1.392    1.392000     1.392
Akron         48.768  136.212200  2724.244
Albuquerque  104.525  158.582857  2220.160
Alexandria    27.025  344.973125  5519.570
...              ...         ...       ...
Woonsocket    48.615   48.887500   195.550
Yonkers       59.520  510.511067  7657.666
York          65.584  163.595600   817.978
Yucaipa       50.800   50.800000    50.800
Yuma         115.192  210.216250   840.865

[529 rows x 3 columns]

In [52]:
country_gap['Sales'].value_counts().head(50)

City         Sales
Aberdeen     25.500      1
Abilene      1.392       1
Akron        21.744      1
             284.364     1
             665.408     1
             149.232     1
             15.936      1
             8.256       1
             25.560      1
             4.368       1
             11.520      1
             221.024     1
             14.952      1
             323.982     1
             2.286       1
             14.352      1
             71.976      1
             85.056      1
             17.184      1
             259.896     1
             247.188     1
             279.960     1
Albuquerque  595.000     1
             79.872      1
             90.800      1
             140.736     1
             214.950     1
             45.360      1
             288.240     1
             23.976      1
             33.290      1
             27.180      1
             118.250     1
             4.280       1
             302.376     1
             255.850     1
Alexandria   22.960      2
             24.560      1
             62.820      1
             489.920     1
             19.440      1
             16.680      1
             155.350     1
             12.420      1
             187.980     1
             81.200      1
             28.990      1
             12.960      1
             4164.050    1
             25.060      1
Name: count, dtype: int64

In [57]:
country_cat=country_gap['Category'].value_counts()

In [59]:
country_cat

City      Category
Aberdeen  Office Supplies     1
Abilene   Office Supplies     1
Akron     Office Supplies    13
          Technology          5
          Furniture           2
                             ..
York      Office Supplies     4
          Furniture           1
Yucaipa   Office Supplies     1
Yuma      Office Supplies     2
          Technology          2
Name: count, Length: 1186, dtype: int64

In [60]:
country_sal=country_gap['Sales'].value_counts()

In [61]:
country_sal

City      Sales
Aberdeen  25.500     1
Abilene   1.392      1
Akron     21.744     1
          284.364    1
          665.408    1
                    ..
Yucaipa   50.800     1
Yuma      44.856     1
          185.528    1
          599.985    1
          10.496     1
Name: count, Length: 9365, dtype: int64

In [66]:
salebycategory=pd.concat([country_sal,country_cat],axis='columns',sort=False)

In [67]:
salebycategory

                          count  count
City
Aberdeen 25.5               1.0    NaN
Abilene  1.392              1.0    NaN
Akron    21.744             1.0    NaN
         284.364            1.0    NaN
         665.408            1.0    NaN
...                         ...    ...
York     Office Supplies    NaN    4.0
         Furniture          NaN    1.0
Yucaipa  Office Supplies    NaN    1.0
Yuma     Office Supplies    NaN    2.0
         Technology         NaN    2.0

[10551 rows x 2 columns]