In [1]:
people={
    'first':['ahmad','zaid','majid'],
    'last':['waleed','ali','gohar'],
    'email':['ahmad@mail.com','zaid@mail.com','majid@mail.com']
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com

In [5]:
peeps={
    'first':['tony','steve'],
    'last':['stark','roger'],
    'email':['tony@mail.com','steve@mail.com']
}

In [6]:
avenger=pd.DataFrame(peeps)

In [7]:
avenger

   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com

In [8]:
df=pd.concat([df,pd.DataFrame([{'first':'Tom','last':'Holand'}])],ignore_index=True)

In [9]:
df

   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com
3    Tom  Holand             NaN

In [10]:
df

   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com
3    Tom  Holand             NaN

In [11]:
avenger

   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com

In [12]:
df is avenger

False

In [13]:
print("DF:")
print(df)

print("\nAVENGER:")
print(avenger)

print("\nDF shape:", df.shape)
print("AVENGER shape:", avenger.shape)

DF:
   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com
3    Tom  Holand             NaN

AVENGER:
   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com

DF shape: (4, 3)
AVENGER shape: (2, 3)

In [14]:
print(df)
print(avenger)
print(df.shape)
print(avenger.shape)

   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com
3    Tom  Holand             NaN
   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com
(4, 3)
(2, 3)

In [15]:
df

   first    last           email
0  ahmad  waleed  ahmad@mail.com
1   zaid     ali   zaid@mail.com
2  majid   gohar  majid@mail.com
3    Tom  Holand             NaN

In [16]:
avenger

   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com

In [17]:
df=pd.concat([df,pd.DataFrame([{'first':'spider','last':'man'}])],ignore_index=True)

In [18]:
df

    first    last           email
0   ahmad  waleed  ahmad@mail.com
1    zaid     ali   zaid@mail.com
2   majid   gohar  majid@mail.com
3     Tom  Holand             NaN
4  spider     man             NaN

In [19]:
avenger=pd.concat([avenger,pd.DataFrame([{'first':'iron','last':'man'}])], ignore_index=True)

In [20]:
avenger

   first   last           email
0   tony  stark   tony@mail.com
1  steve  roger  steve@mail.com
2   iron    man             NaN

In [23]:
df=pd.concat([avenger,df],ignore_index=True)

In [24]:
df

    first    last           email
0    tony   stark   tony@mail.com
1   steve   roger  steve@mail.com
2    iron     man             NaN
3   ahmad  waleed  ahmad@mail.com
4    zaid     ali   zaid@mail.com
5   majid   gohar  majid@mail.com
6     Tom  Holand             NaN
7  spider     man             NaN

In [25]:
filter=df['first']=='spider'
df.drop(index=df[filter].index)

   first    last           email
0   tony   stark   tony@mail.com
1  steve   roger  steve@mail.com
2   iron     man             NaN
3  ahmad  waleed  ahmad@mail.com
4   zaid     ali   zaid@mail.com
5  majid   gohar  majid@mail.com
6    Tom  Holand             NaN

In [26]:
df

    first    last           email
0    tony   stark   tony@mail.com
1   steve   roger  steve@mail.com
2    iron     man             NaN
3   ahmad  waleed  ahmad@mail.com
4    zaid     ali   zaid@mail.com
5   majid   gohar  majid@mail.com
6     Tom  Holand             NaN
7  spider     man             NaN

In [29]:
df.sort_values(by='last', ascending=False)

    first    last           email
3   ahmad  waleed  ahmad@mail.com
0    tony   stark   tony@mail.com
1   steve   roger  steve@mail.com
2    iron     man             NaN
7  spider     man             NaN
5   majid   gohar  majid@mail.com
4    zaid     ali   zaid@mail.com
6     Tom  Holand             NaN

In [30]:
df.sort_values(by=['last','first'], ascending=False)

    first    last           email
3   ahmad  waleed  ahmad@mail.com
0    tony   stark   tony@mail.com
1   steve   roger  steve@mail.com
7  spider     man             NaN
2    iron     man             NaN
5   majid   gohar  majid@mail.com
4    zaid     ali   zaid@mail.com
6     Tom  Holand             NaN

In [31]:
sales=pd.read_csv('../data/dataset.csv')

In [32]:
sales

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [36]:
sales.set_index('Row ID',inplace=True)

In [37]:
sales

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [39]:
sales.sort_value(by='Country')

AttributeError: 'DataFrame' object has no attribute 'sort_value'

In [41]:
sales.sort_values(by='Country', inplace=True)

In [42]:
sales

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [46]:
sales.head(60)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800
8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040
10,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000
11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840
12,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240
13,CA-2018-114412,15/04/2018,20/04/2018,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520
14,CA-2017-161389,05/12/2017,10/12/2017,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,98103.0,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760
15,US-2016-118983,22/11/2016,26/11/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100
16,US-2016-118983,22/11/2016,26/11/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440
17,CA-2015-105893,11/11/2015,18/11/2015,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711.0,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800
18,CA-2015-167164,13/05/2015,15/05/2015,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,Utah,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.5000
19,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.5600
20,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800
21,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,OFF-BI-10002215,Office Supplies,Binders,"Wilson Jones Hanging View Binder, White, 1""",22.7200
22,CA-2017-137330,09/12/2017,13/12/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025.0,Central,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.4600
23,CA-2017-137330,09/12/2017,13/12/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025.0,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.3400
24,US-2018-156909,16/07/2018,18/07/2018,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720
25,CA-2016-106320,25/09/2016,30/09/2016,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057.0,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300
26,CA-2017-121755,16/01/2017,20/01/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049.0,West,OFF-BI-10001634,Office Supplies,Binders,Wilson Jones Active Use Binders,11.6480
27,CA-2017-121755,16/01/2017,20/01/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.5700
28,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300
29,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.6180
30,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.2000
31,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,3.2640
32,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-AR-10004042,Office Supplies,Art,"BOSTON Model 1800 Electric Pencil Sharpeners, ...",86.3040
33,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-BI-10001525,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.8580
34,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-AR-10001683,Office Supplies,Art,Lumber Crayons,15.7600
35,CA-2018-107727,19/10/2018,23/10/2018,Second Class,MA-17560,Matt Abelman,Home Office,United States,Houston,Texas,77095.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.4720
36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440
37,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200
38,CA-2016-117415,27/12/2016,31/12/2016,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.0,Central,OFF-EN-10002986,Office Supplies,Envelopes,"#10-4 1/8"" x 9 1/2"" Premium Diagonal Seam Enve...",113.3280
39,CA-2016-117415,27/12/2016,31/12/2016,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.0,Central,FUR-BO-10002545,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992
40,CA-2016-117415,27/12/2016,31/12/2016,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.0,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.0580
41,CA-2016-117415,27/12/2016,31/12/2016,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.0,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.1680
42,CA-2018-120999,10/09/2018,15/09/2018,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,Illinois,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.1680
43,CA-2017-101343,17/07/2017,22/07/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Los Angeles,California,90049.0,West,OFF-ST-10003479,Office Supplies,Storage,"Eldon Base for stackable storage shelf, platinum",77.8800
44,CA-2018-139619,19/09/2018,23/09/2018,Standard Class,ES-14080,Erin Smith,Corporate,United States,Melbourne,Florida,32935.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.6160
45,CA-2017-118255,11/03/2017,13/03/2017,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122.0,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.9800
46,CA-2017-118255,11/03/2017,13/03/2017,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122.0,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.4600
47,CA-2015-146703,20/10/2015,25/10/2015,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Westland,Michigan,48185.0,Central,OFF-ST-10001713,Office Supplies,Storage,"Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5...",211.9600
48,CA-2017-169194,20/06/2017,25/06/2017,Standard Class,LH-16900,Lena Hernandez,Consumer,United States,Dover,Delaware,19901.0,East,TEC-AC-10002167,Technology,Accessories,Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive,45.0000
49,CA-2017-169194,20/06/2017,25/06/2017,Standard Class,LH-16900,Lena Hernandez,Consumer,United States,Dover,Delaware,19901.0,East,TEC-PH-10003988,Technology,Phones,"LF Elite 3D Dazzle Designer Hard Case Cover, L...",21.8000
50,CA-2016-115742,18/04/2016,22/04/2016,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,Indiana,47150.0,Central,OFF-BI-10004410,Office Supplies,Binders,"C-Line Peel & Stick Add-On Filing Pockets, 8-3...",38.2200
51,CA-2016-115742,18/04/2016,22/04/2016,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,Indiana,47150.0,Central,OFF-LA-10002762,Office Supplies,Labels,Avery 485,75.1800
52,CA-2016-115742,18/04/2016,22/04/2016,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,Indiana,47150.0,Central,FUR-FU-10001706,Furniture,Furnishings,Longer-Life Soft White Bulbs,6.1600
53,CA-2016-115742,18/04/2016,22/04/2016,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,Indiana,47150.0,Central,FUR-CH-10003061,Furniture,Chairs,"Global Leather Task Chair, Black",89.9900
54,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,OFF-FA-10000304,Office Supplies,Fasteners,Advantus Push Pins,15.2600
55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.9500
56,CA-2017-111682,17/06/2017,18/06/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,OFF-ST-10000604,Office Supplies,Storage,Home/Office Personal File Carts,208.5600
57,CA-2017-111682,17/06/2017,18/06/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,OFF-PA-10001569,Office Supplies,Paper,Xerox 232,32.4000
58,CA-2017-111682,17/06/2017,18/06/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,FUR-CH-10003968,Furniture,Chairs,Novimex Turbo Task Chair,319.4100
59,CA-2017-111682,17/06/2017,18/06/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,OFF-PA-10000587,Office Supplies,Paper,"Array Parchment Paper, Assorted Colors",14.5600
60,CA-2017-111682,17/06/2017,18/06/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,TEC-AC-10002167,Technology,Accessories,Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive,30.0000

In [47]:
sales['Country'].head(40)

Row ID
1     United States
2     United States
3     United States
4     United States
5     United States
6     United States
7     United States
8     United States
9     United States
10    United States
11    United States
12    United States
13    United States
14    United States
15    United States
16    United States
17    United States
18    United States
19    United States
20    United States
21    United States
22    United States
23    United States
24    United States
25    United States
26    United States
27    United States
28    United States
29    United States
30    United States
31    United States
32    United States
33    United States
34    United States
35    United States
36    United States
37    United States
38    United States
39    United States
40    United States
Name: Country, dtype: str

In [48]:
sales[['Country','Sales']].head(40)

              Country      Sales
Row ID
1       United States   261.9600
2       United States   731.9400
3       United States    14.6200
4       United States   957.5775
5       United States    22.3680
6       United States    48.8600
7       United States     7.2800
8       United States   907.1520
9       United States    18.5040
10      United States   114.9000
11      United States  1706.1840
12      United States   911.4240
13      United States    15.5520
14      United States   407.9760
15      United States    68.8100
16      United States     2.5440
17      United States   665.8800
18      United States    55.5000
19      United States     8.5600
20      United States   213.4800
21      United States    22.7200
22      United States    19.4600
23      United States    60.3400
24      United States    71.3720
25      United States  1044.6300
26      United States    11.6480
27      United States    90.5700
28      United States  3083.4300
29      United States     9.6180
30      United States   124.2000
31      United States     3.2640
32      United States    86.3040
33      United States     6.8580
34      United States    15.7600
35      United States    29.4720
36      United States  1097.5440
37      United States   190.9200
38      United States   113.3280
39      United States   532.3992
40      United States   212.0580

In [49]:
sales.sort_values(by=['Country','Sales'], ascending=[True,False], inplace=True)

In [50]:
sales

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
2698,CA-2015-145317,18/03/2015,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
6827,CA-2017-118689,02/10/2017,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
8154,CA-2018-140151,23/03/2018,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
2624,CA-2018-127180,22/10/2018,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
4191,CA-2018-166709,17/11/2018,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2107,US-2015-152723,26/09/2015,26/09/2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876
4712,CA-2015-112403,31/03/2015,31/03/2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852
8659,CA-2017-168361,21/06/2017,25/06/2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836
9293,CA-2018-124114,02/03/2018,02/03/2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556
4102,US-2018-102288,19/06/2018,23/06/2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444

In [52]:
df[['Country','Sales']].head(50)

KeyError: "None of [Index(['Country', 'Sales'], dtype='str')] are in the [columns]"

In [53]:
sales[['Country','Sales']].head(40)

              Country      Sales
Row ID
2698    United States  22638.480
6827    United States  17499.950
8154    United States  13999.960
2624    United States  11199.968
4191    United States  10499.970
9040    United States   9892.740
4099    United States   9449.950
4278    United States   9099.930
8489    United States   8749.950
6426    United States   8399.976
2506    United States   8187.650
166     United States   8159.952
684     United States   7999.980
6627    United States   6999.960
510     United States   6354.950
6521    United States   5443.960
7667    United States   5399.910
6341    United States   5199.960
8859    United States   5083.960
5885    United States   4912.590
1086    United States   4899.930
8991    United States   4899.930
4219    United States   4799.984
1804    United States   4663.736
8205    United States   4643.800
2493    United States   4548.810
7819    United States   4535.976
7773    United States   4499.985
9166    United States   4476.800
7244    United States   4416.174
9742    United States   4404.900
4298    United States   4367.896
354     United States   4355.168
9271    United States   4305.552
9640    United States   4297.644
5918    United States   4228.704
3281    United States   4164.050
6621    United States   4164.050
6015    United States   4158.912
6536    United States   4007.840